(TELEGRAM, FIO, FIO_OR_TELEGRAM, FIELD_TO_EDIT, START_DATE, COURSE_TYPE, TOTAL_PAYMENT, PAID_AMOUNT, WAIT_FOR_NEW_VALUE,
 STATISTICS_MENU, COURSE_TYPE_MENU, SELECT_STUDENT, COMMISSION, START_PERIOD, END_PERIOD) = range(15)

# commands/states.py

COMPANY_NAME = "COMPANY_NAME"
SALARY = "SALARY"
COMMISSION = "COMMISSION"
CONFIRMATION = "CONFIRMATION"
STATISTICS_MENU = "STATISTICS_MENU"
COURSE_TYPE_MENU = "COURSE_TYPE_MENU"
NOTIFICATION_MENU = "NOTIFICATION_MENU"
CONFIRM_DELETE = "CONFIRM_DELETE"