(TELEGRAM, FIO, FIO_OR_TELEGRAM, FIELD_TO_EDIT, START_DATE, COURSE_TYPE, SELECT_MENTOR, TOTAL_PAYMENT, PAID_AMOUNT,
 WAIT_FOR_NEW_VALUE, WAIT_FOR_PAYMENT_DATE,
 STATISTICS_MENU, COURSE_TYPE_MENU, SELECT_STUDENT, COMMISSION, START_PERIOD, END_PERIOD,AWAIT_MENTOR_TG, AWAIT_BONUS_AMOUNT,
 EXPENSE_TYPE, EXPENSE_AMOUNT, EXPENSE_DATE, CONFIRM_ASSIGNMENT, WAIT_FOR_DETAILED_SALARY) = range(24)

# commands/states.py

COMPANY_NAME = "COMPANY_NAME"
SALARY = "SALARY"
COMMISSION = "COMMISSION"
CONFIRMATION = "CONFIRMATION"
WAIT_FOR_DETAILED_SALARY = "WAIT_FOR_DETAILED_SALARY"
STATISTICS_MENU = "STATISTICS_MENU"
COURSE_TYPE_MENU = "COURSE_TYPE_MENU"
NOTIFICATION_MENU = "NOTIFICATION_MENU"
CONFIRM_DELETE = "CONFIRM_DELETE"
SIGN_CONTRACT = "SIGN_CONTRACT"
EXPENSE_TYPE = "EXPENSE_TYPE"
EXPENSE_AMOUNT = "EXPENSE_AMOUNT"
EXPENSE_DATE = "EXPENSE_DATE"
MAIN_MENU = "MAIN_MENU"